numerical method documentation
Thrase/Thrase pull request #3
Opened 2024-03-04 03:58 UTC by dyokelson

I still need to resize images so they are less blurry and can make more updates but it's a solid first draft now.

2024-04-05 16:17 UTC, brittany-erickson requested changes

2024-04-05 16:17 UTC, brittany-erickson commented on docs/src/img/BP_schematic_1.jpg
I think we should switch all length scales to L_x, L_y and L_z rather than x_1, x_2, x_3 (which are usually reserved for coordinate directions like x, y, z). Also, change "fault along x_1" to just "fault at x = 0 ". I know we talked about making this more generic but I've been re-thinking it and think that for this benchmark example the domain should just be (x, y, z) in (0, L_x) x (0, L_y) x (0, L_z).  Mostly for notational simplicity - can you update figure to reflect this?  Also change "solving this half... " to "displacement in y-direction".

2024-04-05 16:17 UTC, brittany-erickson commented on docs/src/img/BP_schematic_2.jpg
What do the numbers 2-5 represent? Maybe remove these numbers? Change 3 and 4 to "fault at x = 0" and "slow tectonic loading at x = L_x".  Change "assuming mirrored... " to "anti-symmetric motion".

2024-04-09 00:55 UTC, dyokelson commented on docs/src/img/BP_schematic_1.jpg
done!

2024-04-09 00:55 UTC, dyokelson commented on docs/src/img/BP_schematic_2.jpg
done!

2024-04-09 00:58 UTC, dyokelson commented
> I still need to resize images so they are less blurry and can make more updates but it's a solid first draft now.

done!

2024-04-09 19:43 UTC, merged